import Foundation

struct FixtureSpec {
    let filename: String
    let title: String
    let targetBytes: Int
}

let specs = [
    FixtureSpec(filename: "perf-100kb.md", title: "Performance 100KB Fixture", targetBytes: 90000),
    FixtureSpec(filename: "perf-500kb.md", title: "Performance 500KB Fixture", targetBytes: 500_000),
]

let repositoryRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
let fixturesDirectory = repositoryRoot.appending(path: "Fixtures", directoryHint: .isDirectory)

for spec in specs {
    let text = buildFixture(spec)
    let outputURL = fixturesDirectory.appending(path: spec.filename)
    try text.write(to: outputURL, atomically: true, encoding: .utf8)
    print("\(spec.filename): \(text.utf8.count) bytes")
}

func buildFixture(_ spec: FixtureSpec) -> String {
    let fixtureID = spec.filename.replacingOccurrences(of: ".md", with: "")
    var text = """
    ---
    title: "\(spec.title)"
    description: "Deterministic markdown fixture for Plainsong performance checks."
    date: 2026-06-17
    draft: false
    tags:
      - performance
      - fixture
      - plainsong
    ---

    # \(spec.title)

    This file is generated by `Scripts/generate-perf-fixtures.swift` for repeatable editor,
    preview, file-open, and memory measurements. It keeps Markdown structure stable while
    spreading heavier code and math blocks through the document instead of repeating them
    in every section.

    """

    var section = 1
    while text.utf8.count < spec.targetBytes {
        text += sectionText(section, fixtureID: fixtureID)
        section += 1
    }

    return text
}

func sectionText(_ section: Int, fixtureID: String) -> String {
    let padded = String(format: "%05d", section)
    var text = """

    ## Section \(padded)

    This deterministic paragraph gives the editor ordinary prose to wrap, scan, and highlight.
    It includes **bold text**, *italic text*, `inline code`, [a relative link](./section-\(padded).md),
    and an image reference ![sample](./assets/image-\(padded).png).

    """

    for paragraph in 1 ... 8 {
        text += """

        Paragraph \(paragraph) in section \(padded) keeps the fixture closer to a real long-form
        article: mostly prose with stable wording, enough punctuation for wrapping behavior, and
        predictable sentence length for repeatable preview parsing. Plainsong should handle this
        kind of content smoothly while preserving headings, lists, code samples, math notes, and
        frontmatter around the document. The repeated prose is intentional so performance deltas
        point at renderer behavior instead of changing fixture entropy.

        """
    }

    text += """

    - [ ] Draft checkpoint for section \(padded)
    - [x] Reviewed checkpoint for section \(padded)
    - Nested values: alpha, beta, gamma, delta, epsilon

    > Quoted line for section \(padded) with enough text to exercise source styling, preview anchors,
    > and paragraph wrapping in a stable way.

    """

    if section.isMultiple(of: 6) {
        text += """

        | Column | Value | Notes |
        |---|---:|---|
        | section | \(padded) | repeated table row |
        | words | 72 | stable measurement text |

        """
    }

    if section.isMultiple(of: 5) {
        text += """

        $$
        render_{\(section)} = parse_{\(section)} + highlight_{\(section)} + preview_{\(section)}
        $$

        """
    }

    if section.isMultiple(of: 7) {
        text += """

        ```swift
        struct PerfSection\(padded) {
            let title = "Section \(padded)"
            let tags = ["performance", "markdown", "plainsong"]
        }
        ```

        """
    }

    if section.isMultiple(of: 11) {
        text += """

        ```json
        {"section":"\(padded)","fixture":"\(fixtureID)","stable":true}
        ```

        """
    }

    return text
}
